FROM ubuntu:22.04
USER root

RUN apt-get update && apt-get install -y apt-utils curl

RUN curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io.key | tee \
    /usr/share/keyrings/jenkins-keyring.asc > /dev/null

RUN echo deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \
    https://pkg.jenkins.io/debian-stable binary/ | tee \
    /etc/apt/sources.list.d/jenkins.list > /dev/null

RUN apt-get install -y openjdk-11-jre && apt-get install -y fontconfig openjdk-11-jre

RUN apt-get install -y jenkins

EXPOSE 8088/tcp

CMD ["/bin/bash"]    