# Jenkins Dockerfile
FROM jenkins/jenkins:lts

# Set-up the docker file variables
ARG alias=docker
ARG cert_vol=/certs/client
ARG data_vol=/var/jenkins_home
ARG network=jnet2
ARG port=8082
ARG storage=/app/data/storage/cicd2

# Set the environment variables
ENV DEBIAN_FRONTEND=noninteractive
ENV DOCKER_HOST=tcp://docker:2376 
ENV DOCKER_CERT_PATH=/certs/client 
ENV DOCKER_TLS_VERIFY=1 
ENV JENKINS_HOME=${data_vol}

USER root

# Create the local storage directory if not exists
RUN [ ! -d ${storage} ] && mkdir -p ${storage}

# Install Docker prerequisites
RUN apt-get update && \
    apt-get install -y apt-utils ca-certificates curl gnupg apt-transport-https lsb-release 

# Add Docker's official GPG key
RUN mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg

# Setup Docker repostory
RUN echo \
    "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian \
    $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

# Install Docker packages
RUN apt-get update && apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin

# Create a flat layer
COPY --from=0 / /

EXPOSE ${port} 50000

VOLUME ["${cert_vol}","${data_vol}"]
