# docker-compose.yaml
version: "3.9"
services:
  jenkins:
    build:
        context: /app/data/storage/${app_name}
    container_name: "${app_name}"
    image: jenkins/jenkins:lts
    ports:
        - "${http_port}:8080/tcp"
        - "${agent_port}:50000/tcp"
    privileged: true
    restart: on-failure
    user: root
    networks: 
        - net
    volumes:
        - ${storage}/jenkins_home:${jenkins_home}
        - /var/run/docker.sock:/var/run/docker.sock
    working_dir: "${jenkins_home}"

  agent:
    container_name: agent
    environment:
        - JENKINS_AGENT_SSH_PUBKEY = ${jenkins_agent_ssh_pub_key}
    expose:
        - 22
    image: jenkins/ssh-agent:jdk11
    networks:
        - net
    privileged: true  
    user: root

networks: 
    net:
        driver: bridge

