version: '3'
services:
  jenkins:
    container_name: ${app_name}
    image: jenkins/jenkins:lts-jdk11
    privileged: true
    ports:
      - "${http_port}:8080"
    restart: on-failure
    user: root
    volumes:
      - "${work_dir}/jenkins_home:/var/jenkins_home"
    networks:
      - net

networks:
  net:
