# docker-compose.yaml
version: "3.9"

volumes:
  data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: "${storage}"
    name: ${volume_id}

services:
  jenkins:
    build:
      context: ${context}
      dockerfile: "jenkins.Dockerfile"
    container_name: "${app_name}"
    env_file: 
      - ./.env
    image: "jenkins/jenkins:lts"
    ports:
      - "${http_port}:8080/tcp"
      - "${agent_port}:50000/tcp"
    privileged: true
    restart: on-failure
    user: root
    networks: 
      - net
    volumes:
      - data:${JENKINS_HOME}
    working_dir: "${JENKINS_HOME}"

networks: 
    net:
      driver: bridge
